- content/documentation/tutorials.md
- content/tutorials/exercises/basic.md
- content/tutorials/exercises/conditionals-and-structures.md
- content/tutorials/exercises/functional-programming.md
- sass/site.scss
- templates/shortcodes/question.html
- templates/shortcodes/solution.html
Exercise Tutorial:
The current URL is: http://127.0.0.1:1111/tutorials/exercises/basic
I don't really like the tutorials/exercises in the documentation section BUT for now, it's not possible to add it somewhere else easily. We'll work on another design for the website, in the meanwhile, we could simply leave this new thing/tutorial in the navbar. I don't think it will be a problem, also it will be temporal.
> Exercise Tutorial

- content/documentation/getting-started.md
Fixes incorrect variable names and use classes in the getting started guide.
I stumbled upon this issue when I was updating to v0.4.
> Fixes incorrect variable names and use classes

- content/documentation/data-structures.md
- content/documentation/destructuring.md
- content/documentation/macros.md
- content/documentation/numbers-and-arithmetic.md
- content/documentation/repl.md
- sass/site.scss
- templates/page.html
- templates/page/table-of-content.html
https://github.com/phel-lang/phel-lang.org/issues/19 Since the documentation gets bigger it gets more difficult to navigate it.
- Add a Table of Content (TOC) for doc-pages
> I got a lot of help from here: https://www.getzola.org/documentation/content/table-of-contents/ 
Some examples
> Implement TOC

- sass/_header.scss
- sass/_macros.scss
- sass/_page-toc.scss
- sass/_two-column-layout.scss
- sass/site.scss
- templates/footer.html
- templates/layouts/one-column-layout.html
- templates/layouts/two-column-layout.html
- templates/page.html
- templates/page/table-of-content.html
- Fix the sidebar column to the left side. It is scrollable for smaller screens.
- Anchor links displayed after the header, and not hidden under it.
> Fix sidebar column to left

- content/_index.md
- content/blog/functional-programming-in-php.md
- content/blog/release-0.2.md
- content/blog/release-0.3.md
- content/blog/release-0.4.md
- content/blog/release-0.6.md
- content/documentation/basic-types.md
- content/documentation/configuration.md
- content/documentation/control-flow.md
- content/documentation/data-structures.md
- content/documentation/functions-and-recursion.md
- content/documentation/getting-started.md
- content/documentation/http-request-and-response.md
- content/documentation/in-the-wild.md
- content/documentation/macros.md
- content/documentation/namespaces.md
- content/documentation/php-interop.md
- content/documentation/repl.md
- content/documentation/testing.md
- content/documentation/truth-and-boolean-operations.md
I found some typos, so, I checked all documentation to catch them all 🐭
> Fix some typos in doc

- sass/_site-navigation.scss
- templates/blog-entry.html
Related to: https://github.com/phel-lang/phel-lang.org/issues/33
- Add Previous and Next blog posts at the footer of blog-entry
First blog post
Random blog post in the middle
Last blog post
> Add next/previous links to the blog

- content/documentation/getting-started.md
Add link to Emacs mode for Phel: https://codeberg.org/mmontone/interactive-lang-tools/src/branch/master/backends/phel
> getting-started.md: Add link to ILT Emacs

- content/documentation/getting-started.md
- templates/base.html
- templates/documentation.html
- templates/footer.html
- templates/logo.html
- templates/navigation/site-navigation.html
- templates/page-api.html
- templates/shortcodes/solution.html
Update in `getting started` page the section `Editor support` with `PhpStorm`, also, I replaced the basic `[text](url)` to an HTML `<a href="url" target="_blank">text</a>` in order to add the target attribute, this is done because those links are redirecting the user to an external page.
Also, minor changes like adding some empty spaces or replacing double with single quotes (all content and links still working as before) ✅
> Add phpstorm to editor support

- templates/navigation/top-navigation.html
Currently we lose the underline context if you navigate to another section/page from the current menu.
Zola uses the [Tera](https://tera.netlify.com/) template engine, and I found in its docs that you can [check if a string is starting with another string](https://tera.netlify.app/docs/#starting-with), among many other things. And that solves the current issue that we have in the menu.
Notice the "Docs" is **not** underlined.
Notice the "Docs" **is** underlined.
> Fix underline menu item

- build/src/php/FileGenerator/Domain/ApiMarkdownGenerator.php
- build/src/php/FileGenerator/Domain/ApiSearchGenerator.php
- build/src/php/FileGenerator/Domain/PhelFunctionRepositoryInterface.php
- build/src/php/FileGenerator/Infrastructure/PhelFunctionRepository.php
- build/tests/php/FileGenerator/Domain/ApiMarkdownGeneratorTest.php
- build/tests/php/FileGenerator/Domain/ApiSearchGeneratorTest.php
- composer.lock
Related to https://github.com/phel-lang/phel-lang/pull/565#event-8430281922 we updated the ApiFacade; instead of "grouping the phelFunctions" from the `ApiFacade`, rather move that groupKey as a property of the `PhelFunction` and simplify the signature of the `ApiFacadeInterface`.
- Use the new `ApiFacade::getPhelFunctions()`
The API page and Search logic are generated fine.
> Use the new ApiFacade

- content/documentation/cli-commands.md
In latest Phel version ([0.9](https://github.com/phel-lang/phel-lang/tree/v0.9.0)) we created a new alias for compiling the code for making it more explicit between the ["compiler" module](https://github.com/phel-lang/phel-lang/blob/master/adrs/php/0002_compiler_module.md) & building the code (generating PHP output code) once it was everything compiled.
So, the command `phel compile` still existing, but to make it more clear, it is an alias from `phel build`.
> Rename compile by build in CLI commands section

- content/documentation/basic-types.md
We don't have in the codebase the `Arrays` nor `Tables` types, so, let's drop it from the documentation to avoid misunderstanding.
⚠️ Solves issue https://github.com/phel-lang/phel-lang.org/issues/43
> Drop from basic-types the deprecated array & table types

- content/documentation/configuration.md
Add missing `out-dir`, `keep-generated-temp-files` & `ignore-when-building` keys + some description of each one.
> Add missing keys to configuration section

- composer.json
- sass/_search.scss
- sass/_settings.scss
In the `_search.scss` file it was _globally_ defined
```css
li.selected, li:hover {
text-decoration: underline;
background-color: $color-base-hover;
}
```
So, it was being applied to everywhere a `li` element was in the page, all search CSS is now inside the parent `.site-header__search`.
> Hover only elements from search results

- content/documentation/configuration.md
Updated the docs in accordance to https://github.com/phel-lang/phel-lang/pull/572
> Updated config docs

- content/tutorials/exercises/conditionals-and-structures.md
While it should be clear that the answer is good anyway, it is probably a low hanging fruit to have the question 3 show the exact same strings that are proposed as solution for the questions 3, 4, 5 and 6 anyway, so in this PR I am proposing to fix the capitalization of the strings in the question.
Another point is that when trying the exercise, due to being lowercase, one can think that it is printing the keywords rather than the strings.
> Sync the question with the solution for the conditional exercises

- content/documentation/getting-started.md
I've started to work on phel.vim, a Vim plugin that adds support for the Phel programming language.
It is still under development because I haven't finished it yet; I want to add an indent file so that it proper uses the formatting rules, and I want to add support for `phel format` via an ALE fixer. However, at the moment it already detects *.phel files and enables the phel syntax, which is based on other Lisp-like syntaxes but I've added the list of primitives defined in https://phel-lang.org/documentation/api/ so that it can colour them right away, and add the syntax bits that are specific to Phel and not to other Lisp-like languages, like using \# for comments rather than ;
> Add link to phel.vim in the docs

- content/documentation/macros.md
There seems to be an error in the sample code on the following page.
https://phel-lang.org/documentation/macros/
```
(defmacro mydefn [name args & body]
(list 'def name (apply list 'fn name args body)))
```
When I try to use the above macro, an error occurs.
```
phel:39> (mydefn myinc [a] (inc a))
Second argument of 'fn must be a vector
in string:39
39| (mydefn myinc [a] (inc a))
^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I think the code below is correct, so please check it.
```
(defmacro mydefn [name args & body]
(list 'def name (apply list 'fn args body)))
```
> Fixed the sample code on the macro page

- content/documentation/getting-started.md
The markdown formatter removed double empty lines.
> docs: describe the use of `composer create-project` for getting started

- content/documentation/arithmetic.md
- content/documentation/basic-types.md
- content/documentation/getting-started.md
- content/documentation/truth-and-boolean-operations.md
The "Numbers" section of the "Arithmetic" page was a duplication of the "Numbers" section of the "Basic Types" page.
Ensured that subject and object agreed in number in some descriptions of types.
Fixed some code examples.
Fixed grammar and spelling.
> Improve "Basic Types", "Arithmetic", and "Truth and Boolean" pages

- content/documentation/in-the-wild.md
Add some projects to in-the-wild page.
* [phel-lifegame](https://github.com/smeghead/phel-lifegame) The Lifegame using the CLI terminal written in phel.
* [phel-saraudon](https://github.com/smeghead/phel-saraudon) A command to Visualize result of `git log --stat`.
* [phel-cellular-automaton](https://github.com/smeghead/phel-cellular-automaton) The cellular automaton using the CLI terminal written in phel.
> Add projects to in-the-wild page.

- content/documentation/html-rendering.md
Add for i in (foreach style) rendering example.
Also changed section header to be more general as it was just about rendering lists.
> Improve sequential rendering example section

- templates/layouts/two-column-layout.html
- templates/page-api.html
- templates/page.html
Closes: https://github.com/phel-lang/phel-lang.org/issues/94 
Extract editable block from 2-column-layout and use it only on page template; not on page-api template
Edit me link on pages...
Except API page:
> Edit me link broken at documentation/api

- content/documentation/php-interop.md
Closes: https://github.com/phel-lang/phel-lang.org/issues/90
> Add Accessing super-globals to PHP Interop page

- content/documentation/php-interop.md
Noticed from missing syntax colors in output.
> Add missing code snippet language definition

- content/documentation/control-flow.md
Adds some missing documentation on `for` `:reduce`, minimal example on it's use, plus some general tidying up.
> Improvement on control flow docs

- content/documentation/testing.md
- sass/_header.scss
- sass/_macros.scss
Didn't explain some (very) useful features explained by the command help that might be easier to miss.
> Improve test runner documentation

- content/documentation/global-and-local-bindings.md
- sass/site.scss
- static/back_to_top.js
- templates/base.html
Shown globally and uses theme colors and same border radius value as search-box. Mostly just copy paste from: https://www.w3schools.com/howto/howto_js_scroll_to_top.asp.
Trying to follow theme conventions but didn't think of it too seriously regarding the copy pasted Javascript.
Regarding final styling, the "Top" text could be a arrow up icon and lighter shade of the theme color might be less annoying. Opinions and further edits are welcome but this should be pretty good to get started with.
Also regarding https://github.com/phel-lang/phel-lang.org/issues/99, I thought it's maybe fine to just set this globally instead and not just for API doc page. Maybe change later to be more path specific if it seems annoying.
> Add back to top button & `binding` example

- content/documentation/global-and-local-bindings.md
Add to example how it differs from `let` and move it after `let` section.
> Improve `binding` example

- content/documentation/control-flow.md
Heading arrangement was a bit off. Also changed "Statements (do)" into "Do" as it fits better before Dofor. Maybe upper level heading "Statements" would make sense to sort things with but would require a bit of work, I don't understand this vocabulary that deep.
Old state:
> docs / control-flow: fix exception heading level, rearrange

- content/documentation/in-the-wild.md
I have created a new repository using phel-lang and would like to add it to the in-the-wild page.
- [phel-mml2wav](https://github.com/smeghead/phel-mml2wav) Experimental tool to generate wav format files from MML(Music Macro Language).
> Add project to in-the-wild page. phel-mml2wav

- content/documentation/data-structures.md
I remember scratching my head and doing something silly instead the first time I couldn't find `last` function familiar from Clojure, so I think this should help people find it.
> document peek function returning last item of vector or list

- build/src/php/FileGenerator/Application/ApiSearchGenerator.php
- build/tests/php/FileGenerator/Domain/ApiSearchGeneratorTest.php
- static/search.js
- templates/header.html
Quick experiment for https://github.com/phel-lang/phel-lang.org/issues/123 & https://github.com/phel-lang/phel-lang.org/issues/110. Seems to work mostly with some rough edges.
Modifies `ApiSearchGenerator.php` ran with the existing `composer build` action to also index Markdown files from `content/documentation/` and `search.js` to list the entries with separate template per match type based on new "type" property added in search index results with values "documentation" or "api".
Does some filtering on the markdown content during indexing which probably needs tuning to get best result, also the `search.js` weight settings might need tuning. Claude also though to change `search.js` boolean logic from "AND" to "OR" for more flexible search results, but I did not evaluate that.
Tests were …
> feat: index `contents/documentation/` for search along API

- syntaxes/phel.sublime-syntax
Adds same rule to support `;` as comment character as was added in Phel lexer, so code snippets using it are highlighted correctly after https://github.com/phel-lang/phel-lang.org/pull/126 is merged.
I changed the identifier in `scope: comment.line.hash-or-semicolon.phel` which I'm not sure if it might break something somewhere, but on my basic test things seem to work fine.
> feat: semicolon comment syntax highlighting for website

- content/documentation/functions-and-recursion.md
https://github.com/phel-lang/phel-lang/issues/903#issuecomment-3240318121 by @JesusValeraDev
> Multi-arity function arguments

- content/documentation/basic-types.md
Document (unreleased) PR's https://github.com/phel-lang/phel-lang/pull/914 + https://github.com/phel-lang/phel-lang/pull/915
Closing: https://github.com/phel-lang/phel-lang.org/issues/124
> Semicolon and inline s-expression comments

- static/search.js
- Prevent error when user has no focus while search
- Improve focus following using keyboard arrows
- Handle Esc button keydown
> Improve search ux

- content/documentation/_index.md
- templates/section.html
Closing: https://github.com/phel-lang/phel-lang.org/issues/109
There was this `section.html` template missing. Now that it's added, it could be also utilized better but as it's requires some work for now I added just a simple JS redirect and a link to the Getting Started guide.
> Fix `/documentation` url

- css/components/dark-mode.css
- css/components/layout.css
- templates/base.html
- templates/blog-entry.html
- Fix Prev/Next blog buttons
- Fix Atom/RSS feed
> Small design adjustments

- content/_index.md
- css/components/dark-mode.css
- css/components/features.css
- css/components/header.css
- css/theme.css
- scripts/concat-tailwind.js
- templates/index.html
- templates/shortcodes/feature_card.html
- templates/shortcodes/features.html
From this (pure text and some unnecessary sections)
To this:
> Improve homepage

- css/components/code-block.css
- css/components/dark-mode.css
- css/components/documentation.css
- css/components/features.css
- scripts/concat-tailwind.js
- static/copy-code.js
- templates/base.html
Add copy button on code snippets when hovering the `pre` element
> Add copy button on code snippets

- content/_index.md
- content/documentation/getting-started.md
- css/components/code-block.css
- css/components/dark-mode.css
- css/components/layout.css
- templates/shortcodes/feature_card.html
Solve the broken cards on the homepage, and change some other SVGs.
> Fix cards home

- content/_index.md
- templates/shortcodes/features.html
Remove `features()` template 🤞🏼
> Fix cards home x2

- .gitignore
- build/api-page.php
- build/api-search.php
- build/src/php/FileGenerator/Application/ApiMarkdownGenerator.php
- build/src/php/FileGenerator/Application/ApiSearchGenerator.php
- build/src/php/FileGenerator/DependencyProvider.php
- build/src/php/FileGenerator/Facade.php
- build/src/php/FileGenerator/Factory.php
- build/src/php/FileGenerator/Infrastructure/ApiMarkdownFile.php
- build/src/php/FileGenerator/Infrastructure/ApiSearchFile.php
- build/tests/php/FileGenerator/Domain/ApiMarkdownGeneratorTest.php
- build/tests/php/FileGenerator/Domain/ApiSearchGeneratorTest.php
- build/tests/php/FileGenerator/Integration/ApiMarkdownGeneratorTest.php
- composer.json
I want to create a new module (`VersionUpdater`), so having the namespace defined as `PhelDocBuild` doesn't make sense anymore.
This PR focuses mainly on:
- Update namespace from `composer` and files from `PhelDocBuild` to `PhelWeb`
- Remove incorrectly ignored folders from the `.gitignore` file
- Move integration test (`ApiMarkdownGeneratorTest`) from `test/integration` to `test/FileGenerator/integration` folder
> Update namespace "PhelDocBuildTests" to "PhelWeb"
