phel-lang/phel-lang.org

Readme.md, config.toml, content/documentation/in-the-wild.md, templates/content/documentation/in-the-wild.md
Update documentation with https://github.com/phel-lang/phel-lang/issues/309
=> 309  - Update "in the wild" links

content/documentation/api.md, content/documentation/html-rendering.md, templates/config.toml, templates/public/index.html
- Run `php build/api-page.php > content/documentation/api.md`
- Fix some typos
=> Update api.md & fix some typos

content/tutorials/exercises/advanced.md
- Added requirements and some hints for the advance exercise/game: Rock, paper, scissors
=> Add Rock, paper, scissors advanced exercise

content/documentation/configuration.md, content/documentation/getting-started.md, templates/navigation/top-navigation.html
This updates the documentation for the next release 0.4
Notice: I should merged after 0.4 has been released.
=> Updated documentation for version 0.4

config.toml, content/documentation/configuration.md, content/documentation/global-and-local-bindings.md, content/documentation/html-rendering.md, content/documentation/http-request-and-response.md, content/documentation/interfaces.md, content/documentation/namespaces.md, content/documentation/php-interop.md, content/documentation/repl.md, content/documentation/testing.md, syntaxes/phel.sublime-syntax
* Added documentation for variables
* Added chapter about interfaces
* Added documentation for namespaced keywords
=> Prepare docs for release 0.5.0

build/src/php/FileGenerator/Domain/PhelFnNormalizer.php, build/tests/php/FileGenerator/PhelFnNormalizerTest.php
Add more tests for `PhelFnNormalizerTest` class.
> I didn't create a `test_symbol_with_doc_and_signature` because there is no examples in the API with that configuration.
=> Improve PhelFnNormalizerTest class

config.toml, content/blog/_index.md, content/blog/functional-programming-in-php.md, content/blog/map-filter-reduce.md, content/blog/release-0.1.md, content/blog/release-0.2.md, content/blog/release-0.3.md, content/blog/release-0.4.md, content/blog/release-0.5.md, sass/_post-list.scss, sass/site.scss, templates/base.html, templates/blog-entry.html, templates/blog.html, templates/navigation/top-navigation.html
This add a blog the website.
* I added a simple blog post for each release
* I added a blog post from twitter
* The list of blog post is keep quite simple. We could it improve it in future.
* I added a date to each blog post
* I added a atom xml feed
=> Added inital blog content

sass/_post-list.scss, templates/blog-entry.html, templates/blog.html
Improved the design of the Blog index page
.
=> Improved blog index page

content/blog/release-0.8.md
> Feel free to update these notes and add more details if you want.
=> Add release-0.8 blog post

content/documentation/in-the-wild.md
- Removed phel/json library since we have it as part of the project https://phel-lang.org/blog/release-0-8/
- Added phel-cli-gui library
- Added phel-snake project
=> Update "In the wild" page

content/documentation/configuration.md, content/documentation/debug.md, content/documentation/repl.md
Issue: https://github.com/phel-lang/phel-lang.org/issues/44
Despite we don't have a compatible debug framework (at least yet) we have some strategies to debug phel code, and it would be really useful to share them with the devs in the docs website.
=> Add Debug section under Testing inside Docs

content/documentation/cli-commands.md, content/documentation/commands.md
Issue: https://github.com/phel-lang/phel-lang.org/issues/34
We should add a chapter about the command line tool and describe each command.
=> Add chapter about the command line tool

static/search.js
Issue: https://github.com/phel-lang/phel-lang.org/issues/52
Put the focus on the `search bar` when `s` key is pressed.
=> Focus in search bar when "s" key is pressed

sass/_search.scss, static/search.js, templates/header.html
Issue: https://github.com/phel-lang/phel-lang.org/issues/52
I wanted to be able to scroll up/down using the key arrows in the search input, and when pressing the enter key then go directly to that entry.
> 🏗️ The code needs to be cleaned up, but the proof of concept works 😄 
https://user-images.githubusercontent.com/5256287/216780726-aed3dabe-d9ce-4fdc-84c9-27addeacf825.mov
=> Scroll up/down in search input

content/blog/release-0.9.md
=> Prepare blog entry for release 0.9

content/documentation/cli-commands.md
Feature added in https://github.com/phel-lang/phel-lang/pull/567
=> Add testdox option to test command

content/blog/release-0.10.md
Prepare the blog post for the next release v0.10
Planned for "2023-04-01"
https://user-images.githubusercontent.com/5256287/228640651-d566d2cd-9028-4375-84f5-8da62089efdd.mov
=> Add release-0.10 blog post

content/documentation/authoring-libraries.md
Related to: https://github.com/phel-lang/phel-lang/issues/59
=> feat: adds documentation for library authors

content/documentation/in-the-wild.md
I would like to add my projects to the in-the-wild page.
* Add phel-str library.
* Add zo3ja project.
* Add phel-tic-tac-toe project.
=> Add in-the-wild projects.

content/documentation/in-the-wild.md
I would like to add phel-pdo library to the in-the-wild page.
=> Add phel-pdo to in-the-wild library.

config.toml, sass/_one-column-layout.scss, templates/layouts/two-column-layout.html
Closes: https://github.com/phel-lang/phel-lang.org/issues/45
=> Add "Edit me" links to two-column-layout

content/blog/loop.md
Create a blog post to help resolve errors due to `recur` position.
phel-lang/phel-lang#491
I would like to create a blog post that will help solve the problem regarding the location of `recur`.
=> Add loop blog post

content/documentation/macros.md
=> fix: typo in macros page.

content/documentation/control-flow.md
`Can not resolve type Exception` was given, related issue https://github.com/phel-lang/phel-lang.org/issues/87.
=> Fix example code on exceptions

build/src/php/FileGenerator/Application/ApiMarkdownGenerator.php, composer.json, composer.lock
Related: https://github.com/phel-lang/phel-lang/pull/773 
Closes: https://github.com/phel-lang/phel-lang.org/issues/95
=> Add read more link

.github/workflows/ci.yml, .github/workflows/main.yml
similar as https://github.com/phel-lang/phel-lang/pull/797
=> fix: workflow cache v4

config.toml, css/base.css, css/components/blog.css, css/components/dark-mode.css, css/components/documentation.css, css/components/footer.css, css/components/header.css, css/components/layout.css, css/components/navigation.css, css/components/search.css, css/theme.css, static/mobile-menu.js, static/search.js, templates/documentation.html, templates/footer.html, templates/header.html, templates/layouts/one-column-layout.html, templates/layouts/two-column-layout.html, templates/navigation/top-navigation.html, templates/page-api.html, templates/page.html, templates/section.html
Many idesign mprovements, like:
- Replace background color in dark-mode
- Improve search bar and search result design
- Small design adjustments to API page
- Keep improving design
- Update footer
- Improve button designs from Blog section
=> More design adjustments

css/base.css, css/components/dark-mode.css, css/components/documentation.css, css/components/footer.css, css/components/layout.css, css/components/navigation.css, css/theme.css, templates/blog-entry.html, templates/blog.html, templates/shortcodes/solution.html
=> Change bg and link colors in dark mode

config.toml
=> Update "phel_version" to 0.23.1

css/components/layout.css
Add bottom padding to the sidebar on big screens.
<br/><br/>
✨✨ TO THIS ✨✨ 
<br/><br/>
=> Fix padding sidebar on big screens
